/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v6.0
processor: MIMXRT1052xxxxB
package_id: MIMXRT1052CVL5B
mcu_data: ksdk2_0
processor_version: 6.0.1
functionalGroups:
- name: BOARD_InitPeripherals
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'msg'
- type_id: 'msg_6e2baaf3b97dbeef01c0043275f9a0e7'
- global_messages: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * eDMA initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'eDMA'
- type: 'edma'
- mode: 'basic'
- type_id: 'edma_a23fca76a894e1bcdf9d01a687505ff9'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_edma:
    - common_settings:
      - enableContinuousLinkMode: 'false'
      - enableHaltOnError: 'true'
      - enableRoundRobinArbitration: 'false'
      - enableDebugMode: 'true'
    - dma_table:
      - 0: []
      - 1: []
    - edma_channels: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const edma_config_t eDMA_config = {
  .enableContinuousLinkMode = false,
  .enableHaltOnError = true,
  .enableRoundRobinArbitration = false,
  .enableDebugMode = true
};

void eDMA_init(void) {
}

/***********************************************************************************************************************
 * CORE_BOARD_MODE_KEY initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CORE_BOARD_MODE_KEY'
- type: 'igpio'
- mode: 'GPIO'
- type_id: 'igpio_b1c1fa279aa7069dca167502b8589cb7'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO1'
- config_sets:
  - fsl_gpio:
    - enable_irq_comb_0_15: 'true'
    - gpio_interrupt_comb_0_15:
      - IRQn: 'GPIO1_Combined_0_15_IRQn'
      - enable_priority: 'true'
      - priority: '5'
      - enable_custom_name: 'true'
      - handler_custom_name: 'CORE_BOARD_MODE_KEY_IRQHandler'
    - enable_irq_comb_16_31: 'false'
    - gpio_interrupt_comb_16_31:
      - IRQn: 'GPIO1_Combined_16_31_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'true'
      - handler_custom_name: 'GPIO_COMB_16_31_IRQHANDLER'
    - enable_irq_int0: 'false'
    - gpio_interrupt_int0:
      - IRQn: 'GPIO1_INT0_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int1: 'false'
    - gpio_interrupt_int1:
      - IRQn: 'GPIO1_INT1_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int2: 'false'
    - gpio_interrupt_int2:
      - IRQn: 'GPIO1_INT2_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int3: 'false'
    - gpio_interrupt_int3:
      - IRQn: 'GPIO1_INT3_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int4: 'false'
    - gpio_interrupt_int4:
      - IRQn: 'GPIO1_INT4_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int5: 'false'
    - gpio_interrupt_int5:
      - IRQn: 'GPIO1_INT5_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int6: 'false'
    - gpio_interrupt_int6:
      - IRQn: 'GPIO1_INT6_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int7: 'false'
    - gpio_interrupt_int7:
      - IRQn: 'GPIO1_INT7_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

void CORE_BOARD_MODE_KEY_init(void) {
  /* Make sure, the clock gate for GPIO1 is enabled (e. g. in pin_mux.c) */
  /* Interrupt vector GPIO1_Combined_0_15_IRQn priority settings in the NVIC */
  NVIC_SetPriority(GPIO1_Combined_0_15_IRQn, CORE_BOARD_MODE_KEY_GPIO_COMB_0_15_IRQ_PRIORITY);
  /* Enable interrupt GPIO1_Combined_0_15_IRQn request in the NVIC */
  EnableIRQ(GPIO1_Combined_0_15_IRQn);
}

/***********************************************************************************************************************
 * CORE_BOARD_WAUP_KEY initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CORE_BOARD_WAUP_KEY'
- type: 'igpio'
- mode: 'GPIO'
- type_id: 'igpio_b1c1fa279aa7069dca167502b8589cb7'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO5'
- config_sets:
  - fsl_gpio:
    - enable_irq_comb_0_15: 'true'
    - gpio_interrupt_comb_0_15:
      - IRQn: 'GPIO5_Combined_0_15_IRQn'
      - enable_priority: 'true'
      - priority: '5'
      - enable_custom_name: 'true'
      - handler_custom_name: 'CORE_BOARD_WAUP_KEY_IRQHandler'
    - enable_irq_comb_16_31: 'false'
    - gpio_interrupt_comb_16_31:
      - IRQn: 'GPIO5_Combined_16_31_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

void CORE_BOARD_WAUP_KEY_init(void) {
  /* Make sure, the clock gate for GPIO5 is enabled (e. g. in pin_mux.c) */
  /* Interrupt vector GPIO5_Combined_0_15_IRQn priority settings in the NVIC */
  NVIC_SetPriority(GPIO5_Combined_0_15_IRQn, CORE_BOARD_WAUP_KEY_GPIO_COMB_0_15_IRQ_PRIORITY);
  /* Enable interrupt GPIO5_Combined_0_15_IRQn request in the NVIC */
  EnableIRQ(GPIO5_Combined_0_15_IRQn);
}

/***********************************************************************************************************************
 * LPI2C1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPI2C1'
- type: 'lpi2c'
- mode: 'master'
- type_id: 'lpi2c_db68d4f4f06a22e25ab51fe9bd6db4d2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPI2C1'
- config_sets:
  - main:
    - clockSource: 'Lpi2cClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - interrupt:
      - IRQn: 'LPI2C1_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - quick_selection: 'qs_interrupt'
  - master:
    - mode: 'polling'
    - config:
      - enableMaster: 'true'
      - enableDoze: 'true'
      - debugEnable: 'false'
      - ignoreAck: 'false'
      - pinConfig: 'kLPI2C_2PinOpenDrain'
      - baudRate_Hz: '400000'
      - busIdleTimeout_ns: '0'
      - pinLowTimeout_ns: '0'
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - hostRequest:
        - enable: 'false'
        - source: 'kLPI2C_HostRequestExternalPin'
        - polarity: 'kLPI2C_HostRequestPinActiveHigh'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpi2c_master_config_t LPI2C1_masterConfig = {
  .enableMaster = true,
  .enableDoze = true,
  .debugEnable = false,
  .ignoreAck = false,
  .pinConfig = kLPI2C_2PinOpenDrain,
  .baudRate_Hz = 400000,
  .busIdleTimeout_ns = 0,
  .pinLowTimeout_ns = 0,
  .sdaGlitchFilterWidth_ns = 0,
  .sclGlitchFilterWidth_ns = 0,
  .hostRequest = {
    .enable = false,
    .source = kLPI2C_HostRequestExternalPin,
    .polarity = kLPI2C_HostRequestPinActiveHigh
  }
};

void LPI2C1_init(void) {
  LPI2C_MasterInit(LPI2C1_PERIPHERAL, &LPI2C1_masterConfig, LPI2C1_CLOCK_FREQ);
}

/***********************************************************************************************************************
 * eLCDIF initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'eLCDIF'
- type: 'elcdif'
- mode: 'rgbMode'
- type_id: 'elcdif_1c39bcb43ed1a24bc8980672c7378576'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LCDIF'
- config_sets:
  - fsl_elcdif:
    - config:
      - panelWidthInt: '800'
      - panelHeightInt: '480'
      - hsw: '1'
      - hfp: '22'
      - hbp: '46'
      - vsw: '1'
      - vfp: '22'
      - vbp: '22'
      - frameRate: '60 Hz'
      - polarityFlags_st:
        - vSyncActive: 'kELCDIF_VsyncActiveLow'
        - hSyncActive: 'kELCDIF_HsyncActiveLow'
        - dataEnableActive: 'kELCDIF_DataEnableActiveLow'
        - driveDataClkEdge: 'kELCDIF_DriveDataOnFallingClkEdge'
      - bufferName: 'defaultBuffer'
      - bufferAlign: '64'
      - pixelFormat: 'kELCDIF_PixelFormatRGB565'
      - dataBus: 'kELCDIF_DataBus16Bit'
      - enablePxpHandShake: 'false'
      - start: 'false'
    - isInterruptEnabled: 'true'
    - elcdifInterruptSources: 'kELCDIF_CurFrameDoneInterruptEnable'
    - interrupt:
      - IRQn: 'LCDIF_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* RGB mode configuration */
const elcdif_rgb_mode_config_t eLCDIF_rgbConfig = {
  .panelWidth = ELCDIF_PANEL_WIDTH,
  .panelHeight = ELCDIF_PANEL_HEIGHT,
  .hsw = 1,
  .hfp = 22,
  .hbp = 46,
  .vsw = 1,
  .vfp = 22,
  .vbp = 22,
  .polarityFlags = (kELCDIF_VsyncActiveLow | kELCDIF_HsyncActiveLow | kELCDIF_DataEnableActiveLow | kELCDIF_DriveDataOnFallingClkEdge),
  .bufferAddr = (uint32_t) eLCDIF_Buffer[0],
  .pixelFormat = kELCDIF_PixelFormatRGB565,
  .dataBus = kELCDIF_DataBus16Bit
};
/* RGB buffer */
AT_NONCACHEABLE_SECTION_ALIGN(uint16_t eLCDIF_Buffer[2][ELCDIF_PANEL_HEIGHT][ELCDIF_PANEL_WIDTH], ELCDIF_RGB_BUFFER_ALIGN);

void eLCDIF_init(void) {
  /* RGB mode initialization */
  ELCDIF_RgbModeInit(ELCDIF_PERIPHERAL, &eLCDIF_rgbConfig);
  /* Enable interrupts */
  ELCDIF_EnableInterrupts(ELCDIF_PERIPHERAL, (kELCDIF_CurFrameDoneInterruptEnable));
  /* Enable interrupt LCDIF_IRQn request in the NVIC */
  EnableIRQ(LCDIF_IRQn);
}

/***********************************************************************************************************************
 * LPUART1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART1'
- type: 'lpuart'
- mode: 'edma'
- type_id: 'lpuart_bebe3e12b6ec22bbd14199038f2bf459'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART1'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'BOARD_BootClockRUN'
      - baudRate_Bps: '115200'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStartBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
    - quick_selection: 'QuickSelection1'
  - edmaCfg:
    - edma_channels:
      - enable_rx_edma_channel: 'true'
      - edma_rx_channel:
        - eDMAn: '0'
        - eDMA_source: 'kDmaRequestMuxLPUART1Rx'
        - enable_custom_name: 'false'
      - enable_tx_edma_channel: 'true'
      - edma_tx_channel:
        - eDMAn: '1'
        - eDMA_source: 'kDmaRequestMuxLPUART1Tx'
        - enable_custom_name: 'false'
    - lpuart_edma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'true'
      - callback_fcn: 'LPUART1_UserCallback'
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART1_config = {
  .baudRate_Bps = 115200,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0,
  .rxFifoWatermark = 1,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStartBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true
};
edma_handle_t LPUART1_RX_Handle;
edma_handle_t LPUART1_TX_Handle;
lpuart_edma_handle_t LPUART1_LPUART_eDMA_Handle;

void LPUART1_init(void) {
  LPUART_Init(LPUART1_PERIPHERAL, &LPUART1_config, LPUART1_CLOCK_SOURCE);
  /* Set the source kDmaRequestMuxLPUART1Rx request in the DMAMUX */
  DMAMUX_SetSource(LPUART1_RX_DMAMUX_BASEADDR, LPUART1_RX_DMA_CHANNEL, LPUART1_RX_DMA_REQUEST);
  /* Enable the 0 channel in the DMAMUX */
  DMAMUX_EnableChannel(LPUART1_RX_DMAMUX_BASEADDR, LPUART1_RX_DMA_CHANNEL);
  /* Set the source kDmaRequestMuxLPUART1Tx request in the DMAMUX */
  DMAMUX_SetSource(LPUART1_TX_DMAMUX_BASEADDR, LPUART1_TX_DMA_CHANNEL, LPUART1_TX_DMA_REQUEST);
  /* Enable the 1 channel in the DMAMUX */
  DMAMUX_EnableChannel(LPUART1_TX_DMAMUX_BASEADDR, LPUART1_TX_DMA_CHANNEL);
  /* Create the eDMA LPUART1_RX_Handle handle */
  EDMA_CreateHandle(&LPUART1_RX_Handle, LPUART1_RX_DMA_BASEADDR, LPUART1_RX_DMA_CHANNEL);
  /* Create the eDMA LPUART1_TX_Handle handle */
  EDMA_CreateHandle(&LPUART1_TX_Handle, LPUART1_TX_DMA_BASEADDR, LPUART1_TX_DMA_CHANNEL);
  /* Create the LPUART eDMA handle */
  LPUART_TransferCreateHandleEDMA(LPUART1_PERIPHERAL, &LPUART1_LPUART_eDMA_Handle, LPUART1_UserCallback, NULL, &LPUART1_TX_Handle, &LPUART1_RX_Handle);
}

/***********************************************************************************************************************
 * PIT1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PIT1'
- type: 'pit'
- mode: 'LPTMR_GENERAL'
- type_id: 'pit_a4782ba5223c8a2527ba91aeb2bc4159'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'PIT'
- config_sets:
  - fsl_pit:
    - enableRunInDebug: 'true'
    - enableSharedInterrupt: 'true'
    - sharedInterrupt:
      - IRQn: 'PIT_IRQn'
      - enable_priority: 'true'
      - priority: '5'
      - enable_custom_name: 'false'
    - timingConfig:
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
    - channels:
      - 0:
        - channelNumber: '0'
        - enableChain: 'false'
        - timerPeriod: '500ms'
        - startTimer: 'true'
        - enableInterrupt: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const pit_config_t PIT1_config = {
  .enableRunInDebug = true
};

void PIT1_init(void) {
  /* Initialize the PIT. */
  PIT_Init(PIT1_PERIPHERAL, &PIT1_config);
  /* Set channel 0 period to 500 ms (33000000 ticks). */
  PIT_SetTimerPeriod(PIT1_PERIPHERAL, kPIT_Chnl_0, PIT1_0_TICKS);
  /* Enable interrupts from channel 0. */
  PIT_EnableInterrupts(PIT1_PERIPHERAL, kPIT_Chnl_0, kPIT_TimerInterruptEnable);
  /* Interrupt vector PIT1_IRQN priority settings in the NVIC */
  NVIC_SetPriority(PIT1_IRQN, PIT1_IRQ_PRIORITY);
  /* Enable interrupt PIT1_IRQN request in the NVIC */
  EnableIRQ(PIT1_IRQN);
  /* Start channel 0. */
  PIT_StartTimer(PIT1_PERIPHERAL, kPIT_Chnl_0);
}

/***********************************************************************************************************************
 * SEMC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SEMC'
- type: 'semc'
- mode: 'dcd'
- type_id: 'semc_d3a530ecfc3f527ce59c92b1deb0f7ea'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'SEMC'
- config_sets:
  - fsl_semc:
    - clockConfig:
      - clockSource: 'kSEMC_ClkSrcPeri'
      - clockSourceFreq: 'BOARD_BootClockRUN'
    - semc_config_t:
      - dqsMode: 'kSEMC_Loopbackdqspad'
      - cmdTimeoutCycles: '0'
      - busTimeoutCycles: '0'
    - semc_sdram_config_t:
      - csxPinMux: 'kSEMC_MUXCSX0'
      - semcSdramCs: 'kSEMC_SDRAM_CS0'
      - address: '0x80000000'
      - memsize_kbytes: '32'
      - portSize: 'kSEMC_PortSize16Bit'
      - burstLen: 'kSEMC_Sdram_BurstLen1'
      - columnAddrBitNum: 'kSEMC_SdramColunm_9bit'
      - casLatency: 'kSEMC_LatencyThree'
      - tPrecharge2Act_Ns: '18'
      - tAct2ReadWrite_Ns: '18'
      - tRefreshRecovery_Ns: '127'
      - tWriteRecovery_Ns: '12'
      - tCkeOff_Ns: '42'
      - tAct2Prechage_Ns: '42'
      - tSelfRefRecovery_Ns: '67'
      - tRefresh2Refresh_Ns: '60'
      - tAct2Act_Ns: '60'
      - tPrescalePeriod_Ns: '160'
      - tIdleTimeout_Ns: '0'
      - refreshPeriod_nsPerRow: '64'
      - refreshUrgThreshold: '64'
      - refreshBurstLen: '1'
    - quick_selection: 'SEMC_Type'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

void SEMC_init(void) {
}

/***********************************************************************************************************************
 * ADC1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC1'
- type: 'adc_12b1msps_sar'
- mode: 'ADC_GENERAL'
- type_id: 'adc_12b1msps_sar_6a490e886349a7b2b07bed10ce7b299b'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC1'
- config_sets:
  - fsl_adc:
    - clockConfig:
      - clockSource: 'kADC_ClockSourceAD'
      - clockSourceFreq: 'custom:10 MHz'
      - clockDriver: 'kADC_ClockDriver1'
      - samplePeriodMode: 'kADC_SamplePeriodShort2Clocks'
      - enableAsynchronousClockOutput: 'true'
    - conversionConfig:
      - resolution: 'kADC_Resolution12Bit'
      - hardwareAverageMode: 'kADC_HardwareAverageCount32'
      - enableHardwareTrigger: 'hardware'
      - enableHighSpeed: 'false'
      - enableLowPower: 'false'
      - enableContinuousConversion: 'false'
      - enableOverWrite: 'false'
      - enableDma: 'false'
    - resultingTime: []
    - resultCorrection:
      - doAutoCalibration: 'true'
      - offset: '0'
    - hardwareCompareConfiguration:
      - hardwareCompareMode: 'disabled'
      - value1: '0'
      - value2: '0'
    - enableInterrupt: 'true'
    - adc_interrupt:
      - IRQn: 'ADC1_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - adc_channels_config:
      - 0:
        - channelNumber: 'IN.15'
        - channelName: ''
        - channelGroup: '0'
        - initializeChannel: 'true'
        - enableInterruptOnConversionCompleted: 'true'
      - 1:
        - channelNumber: 'IN.0'
        - channelName: ''
        - channelGroup: '1'
        - initializeChannel: 'true'
        - enableInterruptOnConversionCompleted: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const adc_config_t ADC1_config = {
  .enableOverWrite = false,
  .enableContinuousConversion = false,
  .enableHighSpeed = false,
  .enableLowPower = false,
  .enableLongSample = false,
  .enableAsynchronousClockOutput = true,
  .referenceVoltageSource = kADC_ReferenceVoltageSourceAlt0,
  .samplePeriodMode = kADC_SamplePeriodShort2Clocks,
  .clockSource = kADC_ClockSourceAD,
  .clockDriver = kADC_ClockDriver1,
  .resolution = kADC_Resolution12Bit
};
const adc_channel_config_t ADC1_channels_config[2] = {
  {
    .channelNumber = 15U,
    .enableInterruptOnConversionCompleted = true
  },
  {
    .channelNumber = 0U,
    .enableInterruptOnConversionCompleted = true
  }
};
void ADC1_init(void) {
  /* Initialize ADC1 peripheral. */
  ADC_Init(ADC1_PERIPHERAL, &ADC1_config);
  /* Configure ADC1 peripheral to average 32 conversions in one measurement. */
  ADC_SetHardwareAverageConfig(ADC1_PERIPHERAL, kADC_HardwareAverageCount32);
  /* Perform ADC1 auto calibration. */
  ADC_DoAutoCalibration(ADC1_PERIPHERAL);
  /* Enable ADC1 hardware trigger. */
  ADC_EnableHardwareTrigger(ADC1_PERIPHERAL, true);
  /* Initialize ADC1 channel 15. */
  ADC_SetChannelConfig(ADC1_PERIPHERAL, 0U, &ADC1_channels_config[0]);
  /* Initialize ADC1 channel 0. */
  ADC_SetChannelConfig(ADC1_PERIPHERAL, 1U, &ADC1_channels_config[1]);
  /* Enable interrupt ADC1_IRQn request in the NVIC */
  EnableIRQ(ADC1_IRQN);
}

/***********************************************************************************************************************
 * ADC_ETC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC_ETC'
- type: 'adc_etc'
- mode: 'ADC_ETC_SW'
- type_id: 'adc_etc_f54f0f22e1814a87101dbc3d3da0f030'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC_ETC'
- config_sets:
  - fsl_adc_etc:
    - config:
      - clockConfig_t:
        - clockSource: 'BusInterfaceClock'
        - clockSourceFreq: 'BOARD_BootClockRUN'
        - clockPreDivider: '1'
      - dmaMode: 'kADC_ETC_TrigDMAWithLatchedSignal'
    - tscConfig:
      - enableTSCBypass: 'true'
      - enableTSC0Trigger: 'false'
      - TSC0triggerPriority: '0'
      - enableTSC1Trigger: 'false'
      - TSC1triggerPriority: '0'
    - triggers_config:
      - 0:
        - triggerNameValue: 'TC_0'
        - initializeTrigger: 'true'
        - trigger: 'XBAR0_TRIG.3'
        - triggerPriority: '0'
        - enableSWTriggerMode: 'false'
        - enableSyncMode: 'true'
        - initialDelay_str: '1'
        - sampleIntervalDelay_str: '1'
        - triggerChain:
          - 0:
            - enableB2BMode: 'true'
            - ADCHCRegisterSelect: '0'
            - channelNumber: 'ADC1.IN.15'
            - InterruptEnable: 'kADC_ETC_Done0InterruptEnable'
    - enableInterrupt: 'true'
    - adc_etc_interrupt_0:
      - IRQn: 'ADC_ETC_IRQ0_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'true'
      - handler_custom_name: 'ADC_ETC_0_IRQHANDLER'
    - adc_etc_interrupt_err:
      - IRQn: 'ADC_ETC_ERROR_IRQ_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'true'
      - handler_custom_name: 'ADC_ETC_ERROR_IRQHANDLER'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* ADC_ETC configuration */
const adc_etc_config_t ADC_ETC_config = {
  .clockPreDivider = 1,
  .dmaMode = kADC_ETC_TrigDMAWithLatchedSignal,
  .enableTSCBypass = true,
  .enableTSC0Trigger = false,
  .enableTSC1Trigger = false,
  .TSC0triggerPriority = 0,
  .TSC1triggerPriority = 0,
  .XBARtriggerMask = 8
};
/* ADC_ETC triggers configuration */
const adc_etc_trigger_config_t ADC_ETC_trigger_config[1] = {
  {
    .triggerPriority = 0,
    .enableSWTriggerMode = false,
    .enableSyncMode = true,
    .initialDelay = 1,
    .sampleIntervalDelay = 1,
    .triggerChainLength = 1
  }
};
/* ADC_ETC chain configurations for appropriate (see name of these arrays) trigger configuration */
const adc_etc_trigger_chain_config_t ADC_ETC_TC_0_chain_config[1] = {
  {
    .enableB2BMode = true,
    .ADCHCRegisterSelect = 0,
    .ADCChannelSelect = 15,
    .InterruptEnable = kADC_ETC_Done0InterruptEnable
  }
};

void ADC_ETC_init(void) {
  /* ADC_ETC initialization */
  ADC_ETC_Init(ADC_ETC_PERIPHERAL, &ADC_ETC_config);
  /* Initialize ADC_ETC trigger 3. */
  ADC_ETC_SetTriggerConfig(ADC_ETC_PERIPHERAL, ADC_ETC_TC_0_TG, &ADC_ETC_trigger_config[ADC_ETC_TC_0]);
  /* Initialize ADC_ETC chain configuration for trigger 3. */
  ADC_ETC_SetTriggerChainConfig(ADC_ETC_PERIPHERAL, ADC_ETC_TC_0_TG, 0U, &ADC_ETC_TC_0_chain_config[0]);
  /* Enable interrupt ADC_ETC_IRQ0_IRQn request in the NVIC */
  EnableIRQ(ADC_ETC_IRQ0_IRQn);
  /* Enable interrupt ADC_ETC_ERROR_IRQ_IRQn request in the NVIC */
  EnableIRQ(ADC_ETC_ERROR_IRQ_IRQn);
}

/***********************************************************************************************************************
 * GPT_Timer initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPT_Timer'
- type: 'gpt'
- mode: 'general'
- type_id: 'gpt_e92a0cbd07e389b82a1d19b05eb9fdda'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPT1'
- config_sets:
  - fsl_gpt:
    - gpt_config:
      - clockSource: 'kGPT_ClockSource_Osc'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - oscDivider: '1'
      - divider: '24'
      - enableFreeRun: 'false'
      - enableRunInWait: 'true'
      - enableRunInStop: 'true'
      - enableRunInDoze: 'false'
      - enableRunInDbg: 'false'
      - enableMode: 'true'
    - input_capture_channels: []
    - output_compare_channels:
      - 0:
        - channel: 'kGPT_OutputCompare_Channel1'
        - mode: 'kGPT_OutputOperation_Disconnected'
        - compare_value_str: '1000'
    - interrupt_requests: ''
    - isInterruptEnabled: 'true'
    - interrupt:
      - IRQn: 'GPT1_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'true'
      - handler_custom_name: 'GPT_TIMER_IRQHANDLER'
    - EnableTimerInInit: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const gpt_config_t GPT_Timer_config = {
  .clockSource = kGPT_ClockSource_Osc,
  .divider = 24,
  .enableFreeRun = false,
  .enableRunInWait = true,
  .enableRunInStop = true,
  .enableRunInDoze = false,
  .enableRunInDbg = false,
  .enableMode = true
};

void GPT_Timer_init(void) {
  /* GPT device and channels initialization */
  GPT_Init(GPT_TIMER_PERIPHERAL, &GPT_Timer_config);
  GPT_SetOscClockDivider(GPT_TIMER_PERIPHERAL, 1);
  GPT_SetOutputCompareValue(GPT_TIMER_PERIPHERAL, kGPT_OutputCompare_Channel1, 1000);
  GPT_SetOutputOperationMode(GPT_TIMER_PERIPHERAL, kGPT_OutputCompare_Channel1, kGPT_OutputOperation_Disconnected);
  /* Enable GPT interrupt sources */
  GPT_EnableInterrupts(GPT_TIMER_PERIPHERAL, 0);
  /* Enable interrupt GPT1_IRQn request in the NVIC */
  EnableIRQ(GPT_TIMER_GPT_IRQN);
  /* Start the GPT timer */ 
  GPT_StartTimer(GPT_TIMER_PERIPHERAL);
}

/***********************************************************************************************************************
 * QuadTime3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'QuadTime3'
- type: 'qtmr'
- mode: 'general'
- type_id: 'qtmr_460dd7aa3f3371843c2548acd54252b0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'TMR3'
- config_sets:
  - fsl_qtmr:
    - clockSource: 'BusInterfaceClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - qtmr_channels:
      - 0:
        - channel_prefix_id: 'Channel2'
        - channel: 'kQTMR_Channel_2'
        - primarySource: 'kQTMR_ClockDivide_1'
        - secondarySource: 'kQTMR_Counter0InputPin'
        - countingMode: 'kQTMR_NoOperation'
        - enableMasterMode: 'false'
        - enableExternalForce: 'false'
        - faultFilterCount: '3'
        - faultFilterPeriod: '0'
        - debugMode: 'kQTMR_RunNormalInDebug'
        - timerModeInit: 'pwmOutput'
        - pwmMode:
          - freq_value_str: '1000'
          - dutyCyclePercent: '30'
          - outputPolarity: 'false'
        - dmaIntMode: 'polling'
      - 1:
        - channel_prefix_id: 'Channel3'
        - channel: 'kQTMR_Channel_3'
        - primarySource: 'kQTMR_ClockDivide_1'
        - secondarySource: 'kQTMR_Counter0InputPin'
        - countingMode: 'kQTMR_NoOperation'
        - enableMasterMode: 'false'
        - enableExternalForce: 'false'
        - faultFilterCount: '3'
        - faultFilterPeriod: '0'
        - debugMode: 'kQTMR_RunNormalInDebug'
        - timerModeInit: 'inputCapture'
        - inputCaptureMode:
          - inputPolarity: 'false'
          - reloadOnCapture: 'false'
          - captureMode: 'kQTMR_NoCapture'
        - dmaIntMode: 'interrupt'
        - interrupts: 'kQTMR_EdgeInterruptEnable'
    - interruptVector:
      - enable_irq: 'true'
      - interrupt:
        - IRQn: 'TMR3_IRQn'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const qtmr_config_t QuadTime3_Channel2_config = {
  .primarySource = kQTMR_ClockDivide_1,
  .secondarySource = kQTMR_Counter0InputPin,
  .enableMasterMode = false,
  .enableExternalForce = false,
  .faultFilterCount = 0,
  .faultFilterPeriod = 0,
  .debugMode = kQTMR_RunNormalInDebug
};
const qtmr_config_t QuadTime3_Channel3_config = {
  .primarySource = kQTMR_ClockDivide_1,
  .secondarySource = kQTMR_Counter0InputPin,
  .enableMasterMode = false,
  .enableExternalForce = false,
  .faultFilterCount = 0,
  .faultFilterPeriod = 0,
  .debugMode = kQTMR_RunNormalInDebug
};

void QuadTime3_init(void) {
  /* Quad timer channel Channel2 peripheral initialization */
  QTMR_Init(QUADTIME3_PERIPHERAL, QUADTIME3_CHANNEL2_CHANNEL, &QuadTime3_Channel2_config);
  /* Setup the PWM mode of the timer channel */
  QTMR_SetupPwm(QUADTIME3_PERIPHERAL, QUADTIME3_CHANNEL2_CHANNEL, 132000UL, 30U, false, QUADTIME3_CHANNEL2_CLOCK_SOURCE);
  /* Quad timer channel Channel3 peripheral initialization */
  QTMR_Init(QUADTIME3_PERIPHERAL, QUADTIME3_CHANNEL3_CHANNEL, &QuadTime3_Channel3_config);
  /* Setup the Input capture mode of the timer channel */
  QTMR_SetupInputCapture(QUADTIME3_PERIPHERAL, QUADTIME3_CHANNEL3_CHANNEL, kQTMR_Counter0InputPin, false, false, kQTMR_NoCapture);
  /* Enable interrupt requests of the timer channel */
  QTMR_EnableInterrupts(QUADTIME3_PERIPHERAL, QUADTIME3_CHANNEL3_CHANNEL, kQTMR_EdgeInterruptEnable);
  /* Enable interrupt TMR3_IRQn request in the NVIC */
  EnableIRQ(QUADTIME3_IRQN);
  /* Start the timer - select the timer counting mode */
  QTMR_StartTimer(QUADTIME3_PERIPHERAL, QUADTIME3_CHANNEL2_CHANNEL, kQTMR_NoOperation);
  /* Start the timer - select the timer counting mode */
  QTMR_StartTimer(QUADTIME3_PERIPHERAL, QUADTIME3_CHANNEL3_CHANNEL, kQTMR_NoOperation);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  DMAMUX_Init(EDMA_DMAMUX_BASEADDR);
  EDMA_Init(EDMA_DMA_BASEADDR, &eDMA_config);

  /* Initialize components */
  eDMA_init();
  CORE_BOARD_MODE_KEY_init();
  CORE_BOARD_WAUP_KEY_init();
  LPI2C1_init();
  eLCDIF_init();
  LPUART1_init();
  PIT1_init();
  SEMC_init();
  ADC1_init();
  ADC_ETC_init();
  GPT_Timer_init();
  QuadTime3_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
