/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_B1_08 (coord H13), RGB_RED_LED */
#define BOARD_INITPINS_RGB_RED_LED_GPIO                                    GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_RGB_RED_LED_PORT                                    GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_RGB_RED_LED_PIN                                       24U   /*!< GPIO1 pin index: 24 */

/* GPIO_AD_B1_09 (coord M13), RGB_GREEN_LED */
#define BOARD_INITPINS_RGB_GREEN_LED_GPIO                                  GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_RGB_GREEN_LED_PORT                                  GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_RGB_GREEN_LED_PIN                                     25U   /*!< GPIO1 pin index: 25 */

/* GPIO_AD_B0_10 (coord G13), RGB_BLUE_LED */
#define BOARD_INITPINS_RGB_BLUE_LED_GPIO                                   GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_RGB_BLUE_LED_PORT                                   GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_RGB_BLUE_LED_PIN                                      10U   /*!< GPIO1 pin index: 10 */

/* WAKEUP (coord L6), CORE_BOARD_WAUP_KEY */
#define BOARD_INITPINS_CORE_BOARD_WAUP_KEY_GPIO                            GPIO5   /*!< GPIO device name: GPIO5 */
#define BOARD_INITPINS_CORE_BOARD_WAUP_KEY_PORT                            GPIO5   /*!< PORT device name: GPIO5 */
#define BOARD_INITPINS_CORE_BOARD_WAUP_KEY_PIN                                0U   /*!< GPIO5 pin index: 0 */

/* GPIO_AD_B0_05 (coord G14), CORE_BOARD_MODE_KEY */
#define BOARD_INITPINS_CORE_BOARD_MODE_KEY_GPIO                            GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_CORE_BOARD_MODE_KEY_PORT                            GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_CORE_BOARD_MODE_KEY_PIN                                5U   /*!< GPIO1 pin index: 5 */

/* GPIO_AD_B0_09 (coord F14), CORE_BOARD_LED */
#define BOARD_INITPINS_CORE_BOARD_LED_GPIO                                 GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_CORE_BOARD_LED_PORT                                 GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_CORE_BOARD_LED_PIN                                     9U   /*!< GPIO1 pin index: 9 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
